theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
plugins_dir: _plugins
baseurl: /workers

title: "workers"
description: "workers"
logo: "/assets/logo.png"   # optional
show_downloads: true       # controls the download links in header
github:
  is_user_page: true
  owner_url: "https://github.com/miyako"
  repository_url: "https://github.com/miyako/workers"
  is_project_page: false

exclude:
  - "vendor"
  - "resources"
  - "LICENSE"
  - "README.md"
  - "Gemfile"
